version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lib-layer"
s3_prefix = "lib-layer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-7joab04w50f3"
